### ISSUE TITLE
NPC won't look at player until player moves

### ISSUE THREAD

**Issue by DasBabyPixel** [juliarn/NPC-Lib#109]
When you join any NPC next to you won't look at you until you move, which looks jerky if you stand still for a few seconds waiting for the world to load.
I'd offer to make a PR but the easiest fix would involve listening to the ShowNpcEvent.Post, and that's bad practice(, right?).
Another easy way to fix I didn't find

Anyways, looking at the [CommonNpc](https://github.com/juliarn/NPC-Lib/blob/5bfd22fc895c26cfbf8f12b028bdfe3d7d7d31cd/common/src/main/java/com/github/juliarn/npclib/common/npc/CommonNpc.java#L200) file.

![image](https://github.com/juliarn/NPC-Lib/assets/43410952/6a2ba6c4-2fcc-42ef-af53-900c35d77677)
![image](https://github.com/juliarn/NPC-Lib/assets/43410952/f9906663-ca8d-4ca8-b092-dee237565093)

**Comment by derklaro** [comment]
Yea that's quite unfortunate - I noticed that a few times before. I would not listen to the event in the lib directly, maybe we can offer a method in CommonNpc to simply a position sync for the user?

**Comment by DasBabyPixel** [comment]
Already thought of that but it's not that easy because there is no way to get the distance to the player for the imitateDistance check (in CommonNpc). There is simply no (abstract) method to get the position of the player from the npc-lib-common module

**Comment by derklaro** [comment]
I just took a closer look into the code: there is already an event listener that observes the exact event you wanted to intercept on 1.19.2 and lower to remove the npc from the tablist. So adding an option to make the behaviour opt-out (I guess that a better default than opt-in) to add a listener that rotates the npc into the player direction seems good to me.

Let me know if you want to make a PR for that, otherwise I will take a look to implement that later 😄

**Comment by DasBabyPixel** [comment]
#110
