### ISSUE TITLE
New event api requires java 17

### ISSUE THREAD

**Issue by DasBabyPixel** [juliarn/NPC-Lib#111]
Pretty sure the new event api requires java 17 making it incompatible with 1.8.8
Gradle wouldn't even let me download the [dependency](https://github.com/seiama/event) (until I told it to disableAutoTargetJvm(), which took a while to figure out)

![image](https://github.com/juliarn/NPC-Lib/assets/43410952/909fae63-7b59-4dfe-8859-deb47a55dddc)

**Comment by derklaro** [comment]
Oh shit, I overlooked that - thanks for pointing it out. Nice so that I was able to build a jar targetting Java 8 with a Java 17 dependency 😄 ... I will take a look in the near future, maybe I will just go ahead and implement a simple event bus myself instead of depending on an external dependency for that.

**Comment by derklaro** [comment]
e7e8b0e0e5226983a2ec25b967416508a29eb044 should resolve this, I'm gonna test this later
